import '../styles/styles.css'
import timetable from '../static/timetable.svg'
function Events() {
  const events = [
    {id:1, image:"https://cdn.culture.ru/images/13362809-b7e2-5039-bb4e-110d34c1b9ed",name:'23 февраля',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"23.02.2025"},
    {id:2, image:"https://vzornn.ru/image/news/2022/8-marta.jpg",name:'8 марта',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"8.03.2025"},
    {id:3, image:"https://cs14.pikabu.ru/post_img/2023/05/09/4/og_og_1683606896232965747.jpg",name:'9 мая',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"09.05.2025"},
    {id:4, image:"https://cdn.culture.ru/images/acea02d8-c8be-5c0a-bafd-9b3a3f47ffc5",name:'14 февраля',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"14.02.2025"},
    {id:5, image:"https://avatars.mds.yandex.net/i?id=2b7721a08373227049cf64abf12125b6_l-8995617-images-thumbs&n=13",name:'12 июня',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"12.06.2025"},
    {id:6, image:"https://cdn.culture.ru/images/acea02d8-c8be-5c0a-bafd-9b3a3f47ffc5",name:'14 февраля',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"14.02.2025"},
    {id:7, image:"https://cdn.culture.ru/images/acea02d8-c8be-5c0a-bafd-9b3a3f47ffc5",name:'14 февраля',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"14.02.2025"},
    {id:8, image:"https://cdn.culture.ru/images/acea02d8-c8be-5c0a-bafd-9b3a3f47ffc5",name:'14 февраля',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"14.02.2025"},
    {id:9, image:"https://cdn.culture.ru/images/acea02d8-c8be-5c0a-bafd-9b3a3f47ffc5",name:'14 февраля',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"14.02.2025"},
    {id:10, image:"https://cdn.culture.ru/images/acea02d8-c8be-5c0a-bafd-9b3a3f47ffc5",name:'14 февраля',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"14.02.2025"},
    {id:11, image:"https://cdn.culture.ru/images/acea02d8-c8be-5c0a-bafd-9b3a3f47ffc5",name:'14 февраля',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"14.02.2025"},
    {id:12, image:"https://cdn.culture.ru/images/acea02d8-c8be-5c0a-bafd-9b3a3f47ffc5",name:'14 февраля',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"14.02.2025"},
    {id:13, image:"https://cdn.culture.ru/images/acea02d8-c8be-5c0a-bafd-9b3a3f47ffc5",name:'14 февраля',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"14.02.2025"},
    {id:14, image:"https://cdn.culture.ru/images/acea02d8-c8be-5c0a-bafd-9b3a3f47ffc5",name:'14 февраля',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"14.02.2025"},
    {id:15, image:"https://cdn.culture.ru/images/acea02d8-c8be-5c0a-bafd-9b3a3f47ffc5",name:'14 февраля',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"14.02.2025"},
    {id:16, image:"https://cdn.culture.ru/images/acea02d8-c8be-5c0a-bafd-9b3a3f47ffc5",name:'14 февраля',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"14.02.2025"},
    {id:17, image:"https://cdn.culture.ru/images/acea02d8-c8be-5c0a-bafd-9b3a3f47ffc5",name:'14 февраля',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"14.02.2025"},
    {id:18, image:"https://cdn.culture.ru/images/acea02d8-c8be-5c0a-bafd-9b3a3f47ffc5",name:'14 февраля',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"14.02.2025"},
    {id:19, image:"https://cdn.culture.ru/images/acea02d8-c8be-5c0a-bafd-9b3a3f47ffc5",name:'14 февраля',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"14.02.2025"},
    {id:20, image:"https://cdn.culture.ru/images/acea02d8-c8be-5c0a-bafd-9b3a3f47ffc5",name:'14 февраля',description:'Vestibulum elit est, fringilla eget sodales ac, gravida sed est. Curabitur faucibus ut augue auctor ultrices. Cras fermentum congue vulputate. Donec iaculis nisl ut odio fringilla lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis sed neque eu purus blandit lobortis ut id ipsum. In facilisis hendrerit purus eu cursus.',day_of_week:"14.02.2025"},
   ]
    return (
      <div className='main_container'>
            {events.map(event => (
            <div key={event.id}>
              <div className='events_card'>
              <img src={event.image} alt="event" className='events_card_images'/>
              <p className='events_name'>{event.name}</p>
              <p className='ellipsis'>{event.description}</p>
              <p className='timetable_container'>
              <img src={timetable} alt='timetable_icon' className='timetable_ico'/>
                {event.day_of_week}
              </p>
              </div>
            </div>
          ))}
      </div>
    );
  }
  
  export default Events;
  